# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"    background-color: rgb(49, 54, 59);\n"
"    border-radius: 20px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadow = QtWidgets.QFrame(self.centralwidget)
        self.dropShadow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadow.setObjectName("dropShadow")
        self.lblTitle = QtWidgets.QLabel(self.dropShadow)
        self.lblTitle.setGeometry(QtCore.QRect(20, 50, 641, 101))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(37)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblDesc = QtWidgets.QLabel(self.dropShadow)
        self.lblDesc.setGeometry(QtCore.QRect(20, 130, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.lblDesc.setFont(font)
        self.lblDesc.setStyleSheet("color: rgb(139, 195, 74);")
        self.lblDesc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDesc.setObjectName("lblDesc")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadow)
        self.progressBar.setGeometry(QtCore.QRect(20, 260, 641, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    color: #fff;\n"
"    background-color: rgb(51, 51, 51);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"    font-weight: bold;\n"
"    border-radius: 11px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(31, 71, 32, 255), stop:1 rgba(139, 195, 74, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lblLoading = QtWidgets.QLabel(self.dropShadow)
        self.lblLoading.setGeometry(QtCore.QRect(30, 290, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.lblLoading.setFont(font)
        self.lblLoading.setStyleSheet("color: rgb(139, 195, 74);")
        self.lblLoading.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLoading.setObjectName("lblLoading")
        self.lblCopyright = QtWidgets.QLabel(self.dropShadow)
        self.lblCopyright.setGeometry(QtCore.QRect(20, 340, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.lblCopyright.setFont(font)
        self.lblCopyright.setStyleSheet("color: #eee;")
        self.lblCopyright.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCopyright.setObjectName("lblCopyright")
        self.verticalLayout.addWidget(self.dropShadow)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitle.setText(_translate("MainWindow", "<strong>AT</strong>LAS"))
        self.lblDesc.setText(_translate("MainWindow", "<html><head/><body><p>We solve your <span style=\" font-weight:600;\">PROBLEMS</span></p></body></html>"))
        self.lblLoading.setText(_translate("MainWindow", "loading..."))
        self.lblCopyright.setText(_translate("MainWindow", "Design by <strong>Karm</strong>"))
